server:
  port: 8081

spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 5
      delivery.timeout.ms: 30000
      linger.ms: 5
      batch.size: 16384
      max.in.flight.requests.per.connection: 1
      enable.idempotence: true
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    topic:
      card-expiry-notifications: card-expiry-topic
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_ADDRESS}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    hibernate:
      SQL: debug
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE