CREATE TABLE cards
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    client_id   BIGINT                                  NOT NULL,
    card_number VARCHAR(255)                            NOT NULL,
    issue_date  date,
    expiry_date date,
    status      VARCHAR(255),
    CONSTRAINT pk_cards PRIMARY KEY (id)
);

CREATE TABLE clients
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name  VARCHAR(255),
    middle_name VARCHAR(255),
    last_name   VARCHAR(255),
    birth_date  date,
    email       VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_clients PRIMARY KEY (id)
);

ALTER TABLE cards
    ADD CONSTRAINT uc_cards_cardnumber UNIQUE (card_number);

ALTER TABLE clients
    ADD CONSTRAINT uc_clients_email UNIQUE (email);

ALTER TABLE cards
    ADD CONSTRAINT FK_CARDS_ON_CLIENT FOREIGN KEY (client_id) REFERENCES clients (id);